services:
  # Servicio de Base de Datos (MariaDB)
  espocrm-db:
    image: mariadb:latest
    container_name: espocrm-db
    environment:
      # ¡IMPORTANTE! Cambia estas contraseñas por unas seguras.
      MARIADB_ROOT_PASSWORD: tu_contraseña_root_super_secreta
      MARIADB_DATABASE: espocrm
      MARIADB_USER: espocrm
      MARIADB_PASSWORD: tu_contraseña_db_super_secreta
    volumes:
      - espocrm-db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  # Servicio Principal de EspoCRM (la aplicación web)
  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: espocrm-db
      ESPOCRM_DATABASE_USER: espocrm
      # Usa la misma contraseña que definiste arriba para MARIADB_PASSWORD
      ESPOCRM_DATABASE_PASSWORD: tu_contraseña_db_super_secreta
      ESPOCRM_ADMIN_USERNAME: admin
      # Cambia esta contraseña por una segura para el login de administrador
      ESPOCRM_ADMIN_PASSWORD: tu_contraseña_admin_espo
      ESPOCRM_SITE_URL: "http://localhost:8080"
    volumes:
      - espocrm:/var/www/html
    restart: always
    depends_on:
      espocrm-db:
        condition: service_healthy
    ports:
      - "8080:80"

  # Servicio de Tareas en Segundo Plano
  espocrm-daemon:
    image: espocrm/espocrm
    container_name: espocrm-daemon
    volumes:
      - espocrm:/var/www/html
    restart: always
    entrypoint: docker-daemon.sh

  # Servicio de WebSocket para notificaciones en tiempo real
  espocrm-websocket:
    image: espocrm/espocrm
    container_name: espocrm-websocket
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://localhost:8081"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - espocrm:/var/www/html
    restart: always
    entrypoint: docker-websocket.sh
    ports:
      - "8081:8080"

volumes:
  espocrm-db:
  espocrm: